// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'dialog-close'
  | 'dialog-collection-default'
  | 'dialog-collection-label'
  | 'dialog-crossref-fail'
  | 'dialog-doi-help'
  | 'dialog-doi-invalid'
  | 'dialog-doi-label'
  | 'dialog-doi-missing'
  | 'dialog-doi-placeholder'
  | 'dialog-download-fail'
  | 'dialog-download-success'
  | 'dialog-downloading'
  | 'dialog-item-created'
  | 'dialog-item-exists'
  | 'dialog-mirror-empty'
  | 'dialog-mirror-label'
  | 'dialog-mirror-placeholder'
  | 'dialog-no-pdf'
  | 'dialog-restore'
  | 'dialog-scihub-link'
  | 'dialog-search'
  | 'dialog-title'
  | 'prefs-title';
